services:
  postgres:
    image: postgres:15   # Specify the PostgreSQL version
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: password  # Set the PostgreSQL password
      POSTGRES_DB: tiktok
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data  # Bind the volume for persistent data storage
    deploy:
      resources:
        limits:
          memory: 3g    # Limit memory usage to 2GB
      #     cpus: '1.0'   # Limit CPU usage to 1 CPU core
              #  -c maintenance_work_mem=128MB
              #  -c max_connections=200
              # -c effective_cache_size=768MB
    command: >
      postgres -c shared_buffers=256MB
               -c work_mem=32MB
               -c wal_buffers=16MB
               -c temp_buffers=16MB
    ports:
      - "5432:5432"  # Expose PostgreSQL on the default port
    restart: unless-stopped  # Restart policy